### PR TITLE
Fix exclusion zone length

### PR DESCRIPTION
**Pull request by jtloong**
#6 Changed exclusion zone to be m/4 instead of m/2

### CODE REVIEW

**Comment by vanbenschoten** [comment]
Thanks much for the PR! Did all the tests run successfully? (I really need to add Travis I or Drone to this...)

**Comment by vanbenschoten** [comment]
@jtloong I'm thinking we should actually set the exclusion zone to be a configurable parameter.

**Comment by jtloong** [comment]
Hi there,

You're right it should be a configurable parameter. I can work on that.

In terms of how its working right now with respect to tests, I only got two failures here's the test log:

```
================================== FAILURES ===================================
__________________ TestClass.test_naiveDistanceProfile_self ___________________

self = <tests.test_distanceProfile.TestClass object at 0x000000B231AE8B70>

    def test_naiveDistanceProfile_self(self):
        outcome = (np.array([0.0,2.828,np.inf,np.inf,np.inf,np.inf,np.inf,2.828,0.0]),np.array([4.,4.,4.,4.,4.,4.,4.,4.,4.]))

        b = np.array([0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0])

>       assert(np.round(naiveDistanceProfile(b,4,4),3) == outcome).all()
E       assert False
E        +  where False = <built-in method all of numpy.ndarray object at 0x000000B231A80350>()
E        +    where <built-in method all of numpy.ndarray object at 0x000000B231A80350> = array([[0.   ....   , 4.   ]]) == (array([0.   ,... 4., 4., 4.]))
E             Use -v to get the full diff.all

tests\test_distanceProfile.py:12: AssertionError
---------------------------- Captured stdout call -----------------------------
it works
___________________ TestClass.test_massDistanceProfile_self ___________________

self = <tests.test_distanceProfile.TestClass object at 0x000000B22A2D27B8>

    def test_massDistanceProfile_self(self):
        outcome = (np.array([0.0,2.828,np.inf,np.inf,np.inf,np.inf,np.inf,2.828,0.0]),np.array([4.,4.,4.,4.,4.,4.,4.,4.,4.]))

        b = np.array([0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0])

>       assert(np.round(massDistanceProfile(b,4,4),3) == outcome).all()
E       assert False
E        +  where False = <built-in method all of numpy.ndarray object at 0x000000B231A80300>()
E        +    where <built-in method all of numpy.ndarray object at 0x000000B231A80300> = array([[0.   ....   , 4.   ]]) == (array([0.   ,... 4., 4., 4.]))
E             Use -v to get the full diff.all

tests\test_distanceProfile.py:34: AssertionError
===================== 2 failed, 32 passed in 1.31 seconds =====================
```

I'm having trouble parsing the meaning of the test here. These fail even if I set the exclusion zone length to 2 or 4. Do you know why this is happening?

**Comment by vanbenschoten** [comment]
Did you merge the latest master branch? We updated a couple of tests that weren't working (that would most likely explain the m/2 case). For m/4, I'd actually expect the tests to fail, as a shorter exclusion zone will change the final matrix profile (for these short examples, anyway). I'd say let's set the default parameter to m/2, then include an extra test where the parameter is set to 4 instead of 2.

**Pull request closed without merging**
