### PR TITLE
Feature fluss

### PR DESCRIPTION
**Pull request by mpieters93**
# FLUSS - semantic segmentation using the MPI
This PR adds the  FLUSS algorithm which provides Fast Low-cost Unipotent Semantic Segmentation. It is defined in pseudo-code in MP paper VIII, which I've added as a source in the Readme as well.

This PR changes the following items:
1.  New: _matrixprofile/fluss.py_ defines the fluss function. It returns the Corrected Arc Curve, based on the matrix profile index and the subsequence length.
2.  New: _tests/test_fluss.py_ defines a functionality test.
3.  Changed: _matrixprofile/\_\_init\_\_.py_ now includes fluss.
4.  Changed: _docs/examples/Matrix\_Profile\_Tutorial.ipynb_ now includes an example (plot) of FLUSS.
5. Changed: _README.md_ now includes a reference to the algorithm and the paper.

A nice future feature would be to implement the anytime version of this algorithm (which does produce slightly different results). For now, I think this is already a useful addition. If there are things that need to be improved, please let me know and I'll have a look at them!

### CODE REVIEW

**Comment by vanbenschoten** [comment]
@mpieters93 thank you very much! We'll review this PR shortly.

**Comment by tylerwmarrs** [comment]
This is a really great addition. I have reviewed the code and made some optimizations to it. Please see the attached code for recommended changes. They are primarily optimizations to speed it up.

fluss is your implementation while fluss2 is mine.
image

```python
def fluss2(mpi, m = None):
    """
    Returns the corrected arc curve (CAC) for the matrix profile index (MPI).
    The FLUSS algorithm provides Fast Low-cost Unipotent Semantic Segmantation.

    Parameters
    ----------
    mpi: Matrix profile index accompanying a time series.
    m: Subsequence length that was used to compute the MPI. Note: leaving this empty omits the correction at the head
    and tail of the CAC.
    """
    n = len(mpi)
    corrected_arc_curve = nnmark = np.zeros(n)

    # find the number of arcs crossing over each index
    for i in range(0, n):
        mpi_val = mpi[i]
        small = int(min(i, mpi_val))
        large = int(max(i, mpi_val))
        nnmark[small] = nnmark[small] + 1
        nnmark[large] = nnmark[large] - 1

    # cumulatively sum all crossing arcs at each index
    cross_count = np.cumsum(nnmark)
    
    # compute ideal arc curve for all indices
    idealized = np.apply_along_axis(lambda i: _idealized_arc_curve(n, i), 0, np.arange(0, n))
    idealized = cross_count / idealized
    
    # correct the arc curve so that it is between 0 and 1
    idealized[idealized > 1] = 1
    corrected_arc_curve = idealized
    
    if m:
        corrected_arc_curve[:m] = 1
        corrected_arc_curve[-m:] = 1

    return corrected_arc_curve
```

**Comment by tylerwmarrs** [comment]
It would be pretty trivial to add the algorithm to extract regimes given that we have FLUSS implemented.

**Comment by vanbenschoten** [comment]
@tylerwmarrs agreed. @mpieters93 are you OK with the changes?

**Comment by aouyang1** [comment]
Could we add a small test for the anchor points on the iac? 
Something like the following https://github.com/matrix-profile-foundation/go-matrixprofile/blob/master/matrixprofile/util_test.go#L129

**Comment by mpieters93** [comment]
> This is a really great addition. I have reviewed the code and made some optimizations to it. Please see the attached code for recommended changes. They are primarily optimizations to speed it up with some minor changes to names and additional comments for clarity.
> 
> fluss is your implementation while fluss2 is mine.
> image
> 
> ```python
> def fluss2(mpi, m = None):
> ...
>     return corrected_arc_curve
> ```

Thanks, that looks better indeed!

Upon reviewing the algorithm and the descriptions, I think there might be two (slight) issues that I had not noticed before:

1.  The **nnmark** does not capture "the number of arcs crossing over each index", that is what the **arc_curve** (cross_count in the current code) should capture. I think this stems from an incorrect description in the paper as it says above the pseudo-code:

>  Next, we iterate over the MPIndex to count the number of arcs that cross over index i in lines 3 through 7.

1.  [continued] This seems to be in contrast with (or actually: the same as) the definition of AC (only calculated at line 9 in the pseudo-code) given earlier in the paper:

> The ith index in the AC specifics how many nearest neighbor arcs from the MPIndex spatially cross over location i.

1.  [continued] So if I'm understanding it correctly the **nnmark** captures the number of _additional_ arcs starting to cross at position i. Given this definition, the cumulative sum would indeed provide a correct arc crossings count.

2.  Given the above, an arc starts to count as 'crossing' one step too early. Rather than ``` nnmark[small] = nnmark[small] + 1 ``` we should then do ``` nnmark[small + 1] = nnmark[small] + 1 ```. An easy way to verify is to look at the example attachments I have added. nr. 1 shows the erroneous behavior, nr. 2 shows the correction, nr. 3 shows that this also works for a non-zero example.
### Nr. 1
ex_1
### Nr. 2
ex_2
### Nr. 3
ex_3

As far as I am concerned, everything could be merged after the ``` nnmark[small + 1] = nnmark[small] + 1 ``` is implemented, in addition to the changes proposed by @tylerwmarrs. The values in the test-script should, of course, be updated accordingly as well. I'm going to prepare a commit for all of the above right now.

**Comment by tylerwmarrs** [comment]
@mpieters93 I took a look at the original author's Matlab code and did not see any additional logic to handle such counting ie your "small + 1". Your current implementation of fluss gives the same results as the original Matlab code. Maybe sending an email to the authors will help us get some clarity. You may have found a bug in their implementation as well. 

Here is the link to their code and supporting materials:

https://sites.google.com/site/onlinesemanticsegmentation/

**Comment by mpieters93** [comment]
Thanks for checking @tylerwmarrs! I'll contact the authors, but it probably won't be before the weekend before I get to that.

Just to confirm: do you mean the original Matlab code gives the same result as my original code which did not yet include the "small +1"?

By the way, if anyone has a clue on the potential off-by-one issue, please also don't hesitate to let me know before I contact the original authors.

**Comment by tylerwmarrs** [comment]
@mpieters93 Yes, the code without your suggested fix to the potential bug.

**Comment by mpieters93** [comment]
I have just e-mailed prof. Keogh, I'll let you know when I get a response!

**Comment by vanbenschoten** [comment]
@mpieters93 sounds great!

**Comment by tylerwmarrs** [comment]
@vanbenschoten I think that we could merge this pull request without the potential bug fix and open a new issue. What do you think?

**Comment by vanbenschoten** [comment]
@tylerwmarrs sounds good to me!

**Comment by mpieters93** [comment]
Alright, so an update: prof. Keogh referred me to a colleague of his who did much of the work on the code. She is currently investigating the issue (and my sample code) with the other authors and promised to get back to me.

For now, I think it is great that the feature has already been merged. Just a heads-up: the merged code does contain my suggested bug fix.

**Comment by vanbenschoten** [comment]
@mpieters93 thanks for the update! Keep us posted.

**Comment by vanbenschoten** [comment]
@mpieters93 any update? Did Prof. Keogh's colleague ever get back to you?

**Comment by mpieters93** [comment]
I actually did get a response: they wanted to look into the code/results a bit more and would reply at a later moment. I've just sent an e-mail asking for an update... I'll report back :-)

**Comment by mpieters93** [comment]
@vanbenschoten, I got a message from one of the authors that they looked into it and that there was indeed an off-by-one error in the original implementation. Thanks for your patience in resolving this issue 👍

**Pull request merged**
